
sim:
  max_iterations: 200

#Denavit-Hartenbergs
UR5:
  kinematics:
    theta: [0, 0, 0, 0, 0, 0]  # Joint variables [rad]
    a: [0, -0.425, -0.3922, 0, 0, 0]  # Link lengths [m]
    d: [0.1625, 0, 0, 0.1333, 0.0997, 0.0996]  # Link offsets [m]
    alpha: [1.570796327, 0, 0, 1.570796327, -1.570796327, 0]  # Link twists [rad] (π/2, 0, 0, π/2, -π/2, 0)
  
  dynamics:
    link_1:
      mass: 3.761  # [kg]
      center_of_mass: [0, -0.02561, 0.00193]  # [m]
      inertia_matrix: [0, 0, 0, 0, 0, 0, 0, 0, 0]  # [kg*m^2]
    
    link_2:
      mass: 8.058  # [kg]
      center_of_mass: [0.2125, 0, 0.11336]  # [m]
      inertia_matrix: [0, 0, 0, 0, 0, 0, 0, 0, 0]  # [kg*m^2]
    
    link_3:
      mass: 2.846  # [kg]
      center_of_mass: [0.15, 0.0, 0.0265]  # [m]
      inertia_matrix: [0, 0, 0, 0, 0, 0, 0, 0, 0]  # [kg*m^2]
    
    link_4:
      mass: 1.37  # [kg]
      center_of_mass: [0, -0.0018, 0.01634]  # [m]
      inertia_matrix: [0, 0, 0, 0, 0, 0, 0, 0, 0]  # [kg*m^2]
    
    link_5:
      mass: 1.3  # [kg]
      center_of_mass: [0, 0.0018, 0.01634]  # [m]
      inertia_matrix: [0, 0, 0, 0, 0, 0, 0, 0, 0]  # [kg*m^2]
    
    link_6:
      mass: 0.365  # [kg]
      center_of_mass: [0, 0, -0.001159]  # [m]
      inertia_matrix: [0, 0, 0, 0, 0, 0, 0, 0, 0.0002]  # [kg*m^2]

  source: "https://www.universal-robots.com/developer/hardware-and-motion/robot-motion-dh-parameters/"