/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) six_dof_robot_d90b7393_cost_y_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {11, 1, 1};

/* six_dof_robot_d90b7393_cost_y_fun:(i0[12],i1[6],i2[0],i3[],i4[0])->(o0[11]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42;
  a00=-1.0000000000000001e-01;
  a01=-4.2499999999999999e-01;
  a02=-1.2246467991473532e-16;
  a03=arg[0]? arg[0][0] : 0;
  a04=sin(a03);
  a05=(a02*a04);
  a03=cos(a03);
  a05=(a05-a03);
  a06=arg[0]? arg[0][1] : 0;
  a07=cos(a06);
  a08=(a05*a07);
  a09=(a02*a03);
  a09=(a04+a09);
  a10=-2.0510348974767112e-10;
  a06=sin(a06);
  a11=(a10*a06);
  a12=(a09*a11);
  a08=(a08+a12);
  a12=(a01*a08);
  a13=-3.9224999999999999e-01;
  a14=arg[0]? arg[0][2] : 0;
  a15=cos(a14);
  a16=(a08*a15);
  a17=(a10*a07);
  a18=(a09*a17);
  a05=(a05*a06);
  a18=(a18-a05);
  a14=sin(a14);
  a05=(a18*a14);
  a16=(a16+a05);
  a05=(a13*a16);
  a19=1.0915000000000000e-01;
  a20=(a19*a09);
  a05=(a05-a20);
  a05=(a12+a05);
  a20=-9.4649999999999998e-02;
  a18=(a18*a15);
  a08=(a08*a14);
  a18=(a18-a08);
  a08=arg[0]? arg[0][3] : 0;
  a21=cos(a08);
  a22=(a18*a21);
  a08=sin(a08);
  a23=(a16*a08);
  a22=(a22-a23);
  a23=(a20*a22);
  a24=-1.9413039508976090e-11;
  a25=(a24*a09);
  a23=(a23-a25);
  a23=(a05+a23);
  a25=8.2299999999999998e-02;
  a26=arg[0]? arg[0][4] : 0;
  a27=cos(a26);
  a28=(a10*a27);
  a29=(a22*a28);
  a30=(a09*a27);
  a29=(a29-a30);
  a16=(a16*a21);
  a18=(a18*a08);
  a16=(a16+a18);
  a26=sin(a26);
  a18=(a16*a26);
  a29=(a29-a18);
  a18=(a25*a29);
  a30=-1.6880012166811751e-11;
  a31=(a10*a09);
  a31=(a22+a31);
  a32=(a30*a31);
  a18=(a18-a32);
  a18=(a23+a18);
  a32=casadi_sq(a18);
  a32=(a00*a32);
  a33=1.0000000000000001e-01;
  a34=1.2246467991473532e-16;
  a35=(a34*a03);
  a35=(a35-a04);
  a36=(a35*a07);
  a34=(a34*a04);
  a34=(a34+a03);
  a11=(a34*a11);
  a36=(a36-a11);
  a11=(a01*a36);
  a03=(a36*a15);
  a35=(a35*a06);
  a17=(a34*a17);
  a35=(a35+a17);
  a17=(a35*a14);
  a03=(a03-a17);
  a17=(a13*a03);
  a19=(a19*a34);
  a17=(a17+a19);
  a11=(a11+a17);
  a24=(a24*a34);
  a17=(a03*a08);
  a36=(a36*a14);
  a35=(a35*a15);
  a36=(a36+a35);
  a35=(a36*a21);
  a17=(a17+a35);
  a35=(a20*a17);
  a24=(a24-a35);
  a11=(a11+a24);
  a24=(a34*a27);
  a35=(a17*a28);
  a24=(a24-a35);
  a03=(a03*a21);
  a36=(a36*a08);
  a03=(a03-a36);
  a36=(a03*a26);
  a24=(a24-a36);
  a36=(a25*a24);
  a35=(a10*a34);
  a35=(a17+a35);
  a19=(a30*a35);
  a36=(a36+a19);
  a11=(a11+a36);
  a36=casadi_sq(a11);
  a36=(a33*a36);
  a32=(a32+a36);
  a36=-1.0000000000000000e-02;
  a19=(a36*a18);
  a04=(a19*a11);
  a32=(a32+a04);
  a04=1.0000000000000000e-02;
  a37=(a04*a18);
  a32=(a32+a37);
  a37=(a04*a11);
  a32=(a32+a37);
  a37=8.9159000000000002e-02;
  a01=(a01*a06);
  a01=(a37+a01);
  a38=(a06*a15);
  a39=(a07*a14);
  a38=(a38+a39);
  a13=(a13*a38);
  a39=-2.2387045905958302e-11;
  a13=(a13+a39);
  a13=(a01+a13);
  a07=(a07*a15);
  a06=(a06*a14);
  a07=(a07-a06);
  a06=(a07*a21);
  a14=(a38*a08);
  a06=(a06-a14);
  a20=(a20*a06);
  a14=3.9816821499004115e-21;
  a20=(a20+a14);
  a20=(a13+a20);
  a14=(a06*a28);
  a14=(a14+a28);
  a38=(a38*a21);
  a07=(a07*a08);
  a38=(a38+a07);
  a07=(a38*a26);
  a14=(a14-a07);
  a25=(a25*a14);
  a07=4.2067441506673032e-20;
  a07=(a07-a06);
  a30=(a30*a07);
  a25=(a25+a30);
  a25=(a20+a25);
  a32=(a32-a25);
  if (res[0]!=0) res[0][0]=a32;
  a32=(a18+a18);
  a00=(a00*a32);
  a36=(a36*a11);
  a00=(a00+a36);
  a00=(a00+a04);
  a36=casadi_sq(a00);
  a11=(a11+a11);
  a33=(a33*a11);
  a33=(a33+a19);
  a33=(a33+a04);
  a04=casadi_sq(a33);
  a36=(a36+a04);
  a04=1.;
  a36=(a36+a04);
  a36=sqrt(a36);
  a00=(a00/a36);
  a04=-2.2204460492503136e-16;
  a16=(a16*a27);
  a19=(a10*a26);
  a22=(a22*a19);
  a11=(a09*a26);
  a22=(a22-a11);
  a16=(a16+a22);
  a22=arg[0]? arg[0][5] : 0;
  a11=cos(a22);
  a32=-1.2246467993985324e-16;
  a22=sin(a22);
  a30=(a32*a22);
  a30=(a11+a30);
  a08=(a16*a30);
  a21=(a02*a11);
  a28=(a10*a22);
  a28=(a21+a28);
  a15=(a29*a28);
  a21=(a21-a22);
  a39=(a31*a21);
  a15=(a15-a39);
  a08=(a08+a15);
  a15=(a04*a08);
  a39=-4.9303806576313238e-32;
  a32=(a32*a11);
  a32=(a32-a22);
  a40=(a16*a32);
  a41=(a10*a11);
  a02=(a02*a22);
  a41=(a41-a02);
  a22=(a29*a41);
  a02=(a02+a11);
  a11=(a31*a02);
  a22=(a22+a11);
  a40=(a40+a22);
  a22=(a39*a40);
  a11=1.2246467988961740e-16;
  a16=(a11*a16);
  a42=(a10*a31);
  a29=(a29-a42);
  a16=(a16+a29);
  a22=(a22+a16);
  a15=(a15+a22);
  a00=(a00*a15);
  a33=(a33/a36);
  a03=(a03*a27);
  a34=(a34*a26);
  a17=(a17*a19);
  a34=(a34-a17);
  a03=(a03+a34);
  a34=(a03*a30);
  a17=(a24*a28);
  a26=(a35*a21);
  a17=(a17+a26);
  a34=(a34+a17);
  a34=(a04*a34);
  a17=(a03*a32);
  a26=(a24*a41);
  a15=(a35*a02);
  a26=(a26-a15);
  a17=(a17+a26);
  a17=(a39*a17);
  a03=(a11*a03);
  a35=(a10*a35);
  a24=(a24+a35);
  a03=(a03+a24);
  a17=(a17+a03);
  a34=(a34+a17);
  a33=(a33*a34);
  a00=(a00+a33);
  a33=-1.;
  a33=(a33/a36);
  a38=(a38*a27);
  a06=(a06*a19);
  a06=(a06+a19);
  a38=(a38+a06);
  a30=(a38*a30);
  a28=(a14*a28);
  a21=(a07*a21);
  a28=(a28+a21);
  a30=(a30+a28);
  a04=(a04*a30);
  a32=(a38*a32);
  a41=(a14*a41);
  a02=(a07*a02);
  a41=(a41-a02);
  a32=(a32+a41);
  a39=(a39*a32);
  a11=(a11*a38);
  a38=(a10*a07);
  a14=(a14+a38);
  a11=(a11+a14);
  a39=(a39+a11);
  a04=(a04+a39);
  a33=(a33*a04);
  a00=(a00+a33);
  if (res[0]!=0) res[0][1]=a00;
  a00=-2.2204460492503131e-16;
  a00=(a00*a08);
  a00=(a00+a40);
  if (res[0]!=0) res[0][2]=a00;
  if (res[0]!=0) res[0][3]=a18;
  a25=(a25*a16);
  a18=(a18*a11);
  a25=(a25-a18);
  a18=arg[0]? arg[0][11] : 0;
  a25=(a25*a18);
  a37=(a37*a09);
  a18=arg[0]? arg[0][7] : 0;
  a37=(a37*a18);
  a01=(a01*a09);
  a12=(a10*a12);
  a01=(a01+a12);
  a12=arg[0]? arg[0][8] : 0;
  a01=(a01*a12);
  a37=(a37+a01);
  a13=(a13*a09);
  a10=(a10*a05);
  a13=(a13+a10);
  a10=arg[0]? arg[0][9] : 0;
  a13=(a13*a10);
  a37=(a37+a13);
  a20=(a20*a31);
  a23=(a23*a07);
  a20=(a20+a23);
  a23=arg[0]? arg[0][10] : 0;
  a20=(a20*a23);
  a37=(a37+a20);
  a25=(a25-a37);
  if (res[0]!=0) res[0][4]=a25;
  a25=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][5]=a25;
  a25=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][6]=a25;
  a25=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][7]=a25;
  a25=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][8]=a25;
  a25=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][9]=a25;
  a25=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][10]=a25;
  return 0;
}

CASADI_SYMBOL_EXPORT int six_dof_robot_d90b7393_cost_y_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int six_dof_robot_d90b7393_cost_y_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int six_dof_robot_d90b7393_cost_y_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void six_dof_robot_d90b7393_cost_y_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int six_dof_robot_d90b7393_cost_y_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void six_dof_robot_d90b7393_cost_y_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void six_dof_robot_d90b7393_cost_y_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void six_dof_robot_d90b7393_cost_y_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int six_dof_robot_d90b7393_cost_y_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int six_dof_robot_d90b7393_cost_y_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real six_dof_robot_d90b7393_cost_y_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* six_dof_robot_d90b7393_cost_y_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* six_dof_robot_d90b7393_cost_y_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* six_dof_robot_d90b7393_cost_y_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* six_dof_robot_d90b7393_cost_y_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int six_dof_robot_d90b7393_cost_y_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int six_dof_robot_d90b7393_cost_y_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
