/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) six_dof_robot_0b0392af_constr_h_e_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[3] = {1, 0, 1};

/* six_dof_robot_0b0392af_constr_h_e_fun_jac_uxt_zt:(i0[12],i1[0],i2[0],i3[0])->(o0,o1[12],o2[1x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37;
  a00=2.4305267029519114e+05;
  a01=arg[0]? arg[0][0] : 0;
  a00=(a00*a01);
  a02=1.0608290180238971e+03;
  a03=arg[0]? arg[0][6] : 0;
  a04=(a02*a03);
  a05=(a00+a04);
  a06=(a05*a01);
  a07=2.2689979223259154e+05;
  a08=arg[0]? arg[0][1] : 0;
  a07=(a07*a08);
  a09=8.6499398364348031e+02;
  a10=arg[0]? arg[0][7] : 0;
  a11=(a09*a10);
  a12=(a07+a11);
  a13=(a12*a08);
  a06=(a06+a13);
  a13=1.1012703187225857e+06;
  a14=arg[0]? arg[0][2] : 0;
  a13=(a13*a14);
  a15=2.1256677409024437e+03;
  a16=arg[0]? arg[0][8] : 0;
  a17=(a15*a16);
  a18=(a13+a17);
  a19=(a18*a14);
  a06=(a06+a19);
  a19=1.6575035891518701e+05;
  a20=arg[0]? arg[0][3] : 0;
  a19=(a19*a20);
  a21=2.2163494531262415e+02;
  a22=arg[0]? arg[0][9] : 0;
  a23=(a21*a22);
  a24=(a19+a23);
  a25=(a24*a20);
  a06=(a06+a25);
  a25=1.8778768737889826e+05;
  a26=arg[0]? arg[0][4] : 0;
  a25=(a25*a26);
  a27=4.3653037758571156e+02;
  a28=arg[0]? arg[0][10] : 0;
  a29=(a27*a28);
  a30=(a25+a29);
  a31=(a30*a26);
  a06=(a06+a31);
  a31=1.5288265647899968e+05;
  a32=arg[0]? arg[0][5] : 0;
  a31=(a31*a32);
  a33=9.8730690933225020e+01;
  a34=arg[0]? arg[0][11] : 0;
  a35=(a33*a34);
  a36=(a31+a35);
  a37=(a36*a32);
  a06=(a06+a37);
  a02=(a02*a01);
  a01=9.5181331589231863e+00;
  a01=(a01*a03);
  a37=(a02+a01);
  a03=(a37*a03);
  a06=(a06+a03);
  a09=(a09*a08);
  a08=7.6347324441025606e+00;
  a08=(a08*a10);
  a03=(a09+a08);
  a10=(a03*a10);
  a06=(a06+a10);
  a15=(a15*a14);
  a14=6.5810495422522566e+00;
  a14=(a14*a16);
  a10=(a15+a14);
  a16=(a10*a16);
  a06=(a06+a16);
  a21=(a21*a20);
  a20=2.1957160580151656e+00;
  a20=(a20*a22);
  a16=(a21+a20);
  a22=(a16*a22);
  a06=(a06+a22);
  a27=(a27*a26);
  a26=3.8762078276395076e+00;
  a26=(a26*a28);
  a22=(a27+a26);
  a28=(a22*a28);
  a06=(a06+a28);
  a33=(a33*a32);
  a32=1.3338523993038749e+00;
  a32=(a32*a34);
  a28=(a33+a32);
  a34=(a28*a34);
  a06=(a06+a34);
  if (res[0]!=0) res[0][0]=a06;
  a04=(a04+a05);
  a04=(a04+a00);
  if (res[1]!=0) res[1][0]=a04;
  a11=(a11+a12);
  a11=(a11+a07);
  if (res[1]!=0) res[1][1]=a11;
  a17=(a17+a18);
  a17=(a17+a13);
  if (res[1]!=0) res[1][2]=a17;
  a23=(a23+a24);
  a23=(a23+a19);
  if (res[1]!=0) res[1][3]=a23;
  a29=(a29+a30);
  a29=(a29+a25);
  if (res[1]!=0) res[1][4]=a29;
  a35=(a35+a36);
  a35=(a35+a31);
  if (res[1]!=0) res[1][5]=a35;
  a37=(a37+a01);
  a37=(a37+a02);
  if (res[1]!=0) res[1][6]=a37;
  a03=(a03+a08);
  a03=(a03+a09);
  if (res[1]!=0) res[1][7]=a03;
  a10=(a10+a14);
  a10=(a10+a15);
  if (res[1]!=0) res[1][8]=a10;
  a16=(a16+a20);
  a16=(a16+a21);
  if (res[1]!=0) res[1][9]=a16;
  a22=(a22+a26);
  a22=(a22+a27);
  if (res[1]!=0) res[1][10]=a22;
  a28=(a28+a32);
  a28=(a28+a33);
  if (res[1]!=0) res[1][11]=a28;
  return 0;
}

CASADI_SYMBOL_EXPORT int six_dof_robot_0b0392af_constr_h_e_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int six_dof_robot_0b0392af_constr_h_e_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int six_dof_robot_0b0392af_constr_h_e_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void six_dof_robot_0b0392af_constr_h_e_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int six_dof_robot_0b0392af_constr_h_e_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void six_dof_robot_0b0392af_constr_h_e_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void six_dof_robot_0b0392af_constr_h_e_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void six_dof_robot_0b0392af_constr_h_e_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int six_dof_robot_0b0392af_constr_h_e_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int six_dof_robot_0b0392af_constr_h_e_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real six_dof_robot_0b0392af_constr_h_e_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* six_dof_robot_0b0392af_constr_h_e_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* six_dof_robot_0b0392af_constr_h_e_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* six_dof_robot_0b0392af_constr_h_e_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* six_dof_robot_0b0392af_constr_h_e_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s0;
    case 2: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int six_dof_robot_0b0392af_constr_h_e_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int six_dof_robot_0b0392af_constr_h_e_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
