/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) six_dof_robot_0b0392af_constr_h_e_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {0, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};

/* six_dof_robot_0b0392af_constr_h_e_fun:(i0[12],i1[0],i2[0],i3[0])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20;
  a00=2.4305267029519114e+05;
  a01=arg[0]? arg[0][0] : 0;
  a00=(a00*a01);
  a02=1.0608290180238971e+03;
  a03=arg[0]? arg[0][6] : 0;
  a04=(a02*a03);
  a00=(a00+a04);
  a00=(a00*a01);
  a04=2.2689979223259154e+05;
  a05=arg[0]? arg[0][1] : 0;
  a04=(a04*a05);
  a06=8.6499398364348031e+02;
  a07=arg[0]? arg[0][7] : 0;
  a08=(a06*a07);
  a04=(a04+a08);
  a04=(a04*a05);
  a00=(a00+a04);
  a04=1.1012703187225857e+06;
  a08=arg[0]? arg[0][2] : 0;
  a04=(a04*a08);
  a09=2.1256677409024437e+03;
  a10=arg[0]? arg[0][8] : 0;
  a11=(a09*a10);
  a04=(a04+a11);
  a04=(a04*a08);
  a00=(a00+a04);
  a04=1.6575035891518701e+05;
  a11=arg[0]? arg[0][3] : 0;
  a04=(a04*a11);
  a12=2.2163494531262415e+02;
  a13=arg[0]? arg[0][9] : 0;
  a14=(a12*a13);
  a04=(a04+a14);
  a04=(a04*a11);
  a00=(a00+a04);
  a04=1.8778768737889826e+05;
  a14=arg[0]? arg[0][4] : 0;
  a04=(a04*a14);
  a15=4.3653037758571156e+02;
  a16=arg[0]? arg[0][10] : 0;
  a17=(a15*a16);
  a04=(a04+a17);
  a04=(a04*a14);
  a00=(a00+a04);
  a04=1.5288265647899968e+05;
  a17=arg[0]? arg[0][5] : 0;
  a04=(a04*a17);
  a18=9.8730690933225020e+01;
  a19=arg[0]? arg[0][11] : 0;
  a20=(a18*a19);
  a04=(a04+a20);
  a04=(a04*a17);
  a00=(a00+a04);
  a02=(a02*a01);
  a01=9.5181331589231863e+00;
  a01=(a01*a03);
  a02=(a02+a01);
  a02=(a02*a03);
  a00=(a00+a02);
  a06=(a06*a05);
  a05=7.6347324441025606e+00;
  a05=(a05*a07);
  a06=(a06+a05);
  a06=(a06*a07);
  a00=(a00+a06);
  a09=(a09*a08);
  a08=6.5810495422522566e+00;
  a08=(a08*a10);
  a09=(a09+a08);
  a09=(a09*a10);
  a00=(a00+a09);
  a12=(a12*a11);
  a11=2.1957160580151656e+00;
  a11=(a11*a13);
  a12=(a12+a11);
  a12=(a12*a13);
  a00=(a00+a12);
  a15=(a15*a14);
  a14=3.8762078276395076e+00;
  a14=(a14*a16);
  a15=(a15+a14);
  a15=(a15*a16);
  a00=(a00+a15);
  a18=(a18*a17);
  a17=1.3338523993038749e+00;
  a17=(a17*a19);
  a18=(a18+a17);
  a18=(a18*a19);
  a00=(a00+a18);
  if (res[0]!=0) res[0][0]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int six_dof_robot_0b0392af_constr_h_e_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int six_dof_robot_0b0392af_constr_h_e_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int six_dof_robot_0b0392af_constr_h_e_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void six_dof_robot_0b0392af_constr_h_e_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int six_dof_robot_0b0392af_constr_h_e_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void six_dof_robot_0b0392af_constr_h_e_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void six_dof_robot_0b0392af_constr_h_e_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void six_dof_robot_0b0392af_constr_h_e_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int six_dof_robot_0b0392af_constr_h_e_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int six_dof_robot_0b0392af_constr_h_e_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real six_dof_robot_0b0392af_constr_h_e_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* six_dof_robot_0b0392af_constr_h_e_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* six_dof_robot_0b0392af_constr_h_e_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* six_dof_robot_0b0392af_constr_h_e_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* six_dof_robot_0b0392af_constr_h_e_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int six_dof_robot_0b0392af_constr_h_e_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int six_dof_robot_0b0392af_constr_h_e_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
