/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) six_dof_robot_c6e18385_dyn_disc_phi_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[45] = 
  {18, 12, 0, 3, 6, 9, 12, 15,
  18, 20, 22, 24, 26, 28, 30, 0,
  6, 12, 1, 7, 13, 2, 8, 14,
  3, 9, 15, 4, 10, 16, 5, 11,
  17, 0, 12, 1, 13, 2, 14, 3,
  15, 4, 16, 5, 17};

/* six_dof_robot_c6e18385_dyn_disc_phi_fun_jac:(i0[12],i1[6],i2[0])->(o0[12],o1[18x12,30nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25;
  a00=arg[0]? arg[0][0] : 0;
  a01=4.7244853591162263e-04;
  a02=arg[0]? arg[0][6] : 0;
  a03=(a01*a02);
  a00=(a00+a03);
  a03=2.7551464088377382e-05;
  a04=arg[1]? arg[1][0] : 0;
  a05=(a03*a04);
  a00=(a00+a05);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][1] : 0;
  a05=4.6862413491790753e-04;
  a06=arg[0]? arg[0][7] : 0;
  a07=(a05*a06);
  a00=(a00+a07);
  a07=3.1375865082092485e-05;
  a08=arg[1]? arg[1][1] : 0;
  a09=(a07*a08);
  a00=(a00+a09);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][2] : 0;
  a09=4.4056986587774085e-04;
  a10=arg[0]? arg[0][8] : 0;
  a11=(a09*a10);
  a00=(a00+a11);
  a11=5.9430134122259162e-05;
  a12=arg[1]? arg[1][2] : 0;
  a13=(a11*a12);
  a00=(a00+a13);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[0]? arg[0][3] : 0;
  a13=4.1719793918508014e-04;
  a14=arg[0]? arg[0][9] : 0;
  a15=(a13*a14);
  a00=(a00+a15);
  a15=8.2802060814919870e-05;
  a16=arg[1]? arg[1][3] : 0;
  a17=(a15*a16);
  a00=(a00+a17);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[0]? arg[0][4] : 0;
  a17=4.4991447253424203e-04;
  a18=arg[0]? arg[0][10] : 0;
  a19=(a17*a18);
  a00=(a00+a19);
  a19=5.0085527465757980e-05;
  a20=arg[1]? arg[1][4] : 0;
  a21=(a19*a20);
  a00=(a00+a21);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[0]? arg[0][5] : 0;
  a21=3.4810302741057901e-04;
  a22=arg[0]? arg[0][11] : 0;
  a23=(a21*a22);
  a00=(a00+a23);
  a23=1.5189697258942100e-04;
  a24=arg[1]? arg[1][5] : 0;
  a25=(a23*a24);
  a00=(a00+a25);
  if (res[0]!=0) res[0][5]=a00;
  a00=8.9185653012982957e-01;
  a02=(a00*a02);
  a25=1.0814346987017043e-01;
  a04=(a25*a04);
  a02=(a02+a04);
  if (res[0]!=0) res[0][6]=a02;
  a02=8.7717830047936562e-01;
  a06=(a02*a06);
  a04=1.2282169952063438e-01;
  a08=(a04*a08);
  a06=(a06+a08);
  if (res[0]!=0) res[0][7]=a06;
  a06=7.7209320838144468e-01;
  a10=(a06*a10);
  a08=2.2790679161855532e-01;
  a12=(a08*a12);
  a10=(a10+a12);
  if (res[0]!=0) res[0][8]=a10;
  a10=6.8816957233550369e-01;
  a14=(a10*a14);
  a12=3.1183042766449631e-01;
  a16=(a12*a16);
  a14=(a14+a16);
  if (res[0]!=0) res[0][9]=a14;
  a14=8.0658176825752936e-01;
  a18=(a14*a18);
  a16=1.9341823174247064e-01;
  a20=(a16*a20);
  a18=(a18+a20);
  if (res[0]!=0) res[0][10]=a18;
  a18=4.6122005829500223e-01;
  a22=(a18*a22);
  a20=5.3877994170499777e-01;
  a24=(a20*a24);
  a22=(a22+a24);
  if (res[0]!=0) res[0][11]=a22;
  if (res[1]!=0) res[1][0]=a03;
  a03=1.;
  if (res[1]!=0) res[1][1]=a03;
  if (res[1]!=0) res[1][2]=a01;
  if (res[1]!=0) res[1][3]=a07;
  if (res[1]!=0) res[1][4]=a03;
  if (res[1]!=0) res[1][5]=a05;
  if (res[1]!=0) res[1][6]=a11;
  if (res[1]!=0) res[1][7]=a03;
  if (res[1]!=0) res[1][8]=a09;
  if (res[1]!=0) res[1][9]=a15;
  if (res[1]!=0) res[1][10]=a03;
  if (res[1]!=0) res[1][11]=a13;
  if (res[1]!=0) res[1][12]=a19;
  if (res[1]!=0) res[1][13]=a03;
  if (res[1]!=0) res[1][14]=a17;
  if (res[1]!=0) res[1][15]=a23;
  if (res[1]!=0) res[1][16]=a03;
  if (res[1]!=0) res[1][17]=a21;
  if (res[1]!=0) res[1][18]=a25;
  if (res[1]!=0) res[1][19]=a00;
  if (res[1]!=0) res[1][20]=a04;
  if (res[1]!=0) res[1][21]=a02;
  if (res[1]!=0) res[1][22]=a08;
  if (res[1]!=0) res[1][23]=a06;
  if (res[1]!=0) res[1][24]=a12;
  if (res[1]!=0) res[1][25]=a10;
  if (res[1]!=0) res[1][26]=a16;
  if (res[1]!=0) res[1][27]=a14;
  if (res[1]!=0) res[1][28]=a20;
  if (res[1]!=0) res[1][29]=a18;
  return 0;
}

CASADI_SYMBOL_EXPORT int six_dof_robot_c6e18385_dyn_disc_phi_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int six_dof_robot_c6e18385_dyn_disc_phi_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int six_dof_robot_c6e18385_dyn_disc_phi_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void six_dof_robot_c6e18385_dyn_disc_phi_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int six_dof_robot_c6e18385_dyn_disc_phi_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void six_dof_robot_c6e18385_dyn_disc_phi_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void six_dof_robot_c6e18385_dyn_disc_phi_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void six_dof_robot_c6e18385_dyn_disc_phi_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int six_dof_robot_c6e18385_dyn_disc_phi_fun_jac_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int six_dof_robot_c6e18385_dyn_disc_phi_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real six_dof_robot_c6e18385_dyn_disc_phi_fun_jac_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* six_dof_robot_c6e18385_dyn_disc_phi_fun_jac_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* six_dof_robot_c6e18385_dyn_disc_phi_fun_jac_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* six_dof_robot_c6e18385_dyn_disc_phi_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* six_dof_robot_c6e18385_dyn_disc_phi_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int six_dof_robot_c6e18385_dyn_disc_phi_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int six_dof_robot_c6e18385_dyn_disc_phi_fun_jac_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
